### ISSUE TITLE
Plugin breaks rest api for projects

### ISSUE THREAD

**Issue by erikkallen** [MischaTheEvil/projects_tree_view#9]
If I enable the plugin and request rest interface data for example http://mydomain.com/projects.xml all I get is html response
the same goes for json.
This does not happen when the plugin is disabled

**Comment by erikkallen** [comment]
Found the solution you have to copy the files from chili/app/projects/view/index.api.rsb and chili/app/projects/view/show.api.rsb to plugin/app/projects/view

**Comment by hameno** [comment]
This should be fixed, imho.

Fix for Redmine 1.2.2
Copy 

> index.api.rsb
> show.api.rsb

from

> app/views/projects

to

> vendor/plugins/projects_tree_view/app/views/projects/
